### ISSUE TITLE
Erros no ServiceForms.pm

### ISSUE THREAD

**Issue by mfmatos** [LigeroSmart/ligerosmart#106]
Logs:

web_1            | 10.111.2.6 - - [04/Aug/2021:19:00:42 -0300] "POST /otrs/index.pl HTTP/1.1" 302 97 "http://localhost:8008/otrs/index.pl" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
web_1            | ERROR: OTRS-CGI-10 Perl: 5.30.0 OS: linux Time: Wed Aug 4 22:00:42 2021
web_1            | 
web_1            |  Message: syntax error at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 185, near "if exists"
web_1            | Global symbol "$CurrentField" requires explicit package name (did you forget to declare "my $CurrentField"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 186.
web_1            | Global symbol "$DynamicFieldName" requires explicit package name (did you forget to declare "my $DynamicFieldName"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 187.
web_1            | Global symbol "$CurrentField" requires explicit package name (did you forget to declare "my $CurrentField"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 188.
web_1            | Global symbol "$DynamicFieldName" requires explicit package name (did you forget to declare "my $DynamicFieldName"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 189.
web_1            | Global symbol "$ConfigObject" requires explicit package name (did you forget to declare "my $ConfigObject"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 197.
web_1            | Global symbol "$Action" requires explicit package name (did you forget to declare "my $Action"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 198.
web_1            | Global symbol "%HashDosCampos" requires explicit package name (did you forget to declare "my %HashDosCampos"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 199.
web_1            | Global symbol "$Self" requires explicit package name (did you forget to declare "my $Self"?) at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 202.
web_1            | syntax error at /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm line 203, near "}"
web_1            | /opt/otrs/bin/cgi-bin/../../Kernel/Modules/ServiceForms.pm has too many errors.
web_1            | Compilation failed in require at /opt/otrs/bin/cgi-bin/../../Kernel/System/Main.pm line 85.

**Comment by richieri** [comment]
Corrigido com commit https://github.com/LigeroSmart/ligerosmart/commit/eca2971762ea32b216c73002bfbea8107f2eb678
Será disponibilizado na 6.1.10
