### ISSUE TITLE
Timeout ao processar mensagem com anexos em HTML

### ISSUE THREAD

**Issue by mfmatos** [LigeroSmart/ligerosmart#149]
https://github.com/LigeroSmart/ligerosmart/blob/c89533c16bd34001173df08d5464c84e19a4b1c7/Kernel/System/PostMaster/Filter/DetectAttachment.pm#L63

O sistema pára nesta linha ao processar arquivo anexo grande. Ele trava o MailAccountFetch e o sistema não baixa mais mensagens.

**Comment by richieri** [comment]
https://stackoverflow.com/questions/7464895/regex-taking-a-long-time
