### ISSUE TITLE
Ligerosmart web address

### ISSUE THREAD

**Issue by bschmalhofer** [LigeroSmart/ligerosmart#189]
Hi, 

I've just come accross your fork of the OTRS ((Community Edition)). I wanted to go to your website https://ligerosmat.com/ but found that an 'r' is missing there. https://ligerosmart.com/ does work.

Best regards,
   Bernhard

**Comment by mfmatos** [comment]
Hi,
Thanks for report. Where exactly is this address posted?

**Comment by mfmatos** [comment]
Ops... I found it
![Captura de tela de 2021-11-18 17-20-56](https://user-images.githubusercontent.com/46325500/142490869-22599488-2c84-4b80-9d33-992f18140f73.png)

**Comment by mfmatos** [comment]
OK. Fixed.


![Captura de tela de 2021-11-18 17-22-36](https://user-images.githubusercontent.com/46325500/142491102-712eba07-e1a2-4dcf-88fa-f07569e53b21.png)


Thanks @bschmalhofer
