### ISSUE TITLE
ícones do font awesome

### ISSUE THREAD

**Issue by mfmatos** [LigeroSmart/ligerosmart#24]
Não carrega os ícones nas caixas de busca no cabeçalho. O ícone de 'loading' também não aparece no formulário de abertura de chamado (ícone que aparece ao lado dos campos ao selecionar as opções)

![build2_create-new-service_d89666f30ef6bce54ddf017aa9df611ef03bccb1](https://user-images.githubusercontent.com/46325500/108772927-64872c80-753c-11eb-9a9c-8d4eaca5679c.png)

**Comment by richieri** [comment]
Fiz o commit 7e49489425dc3fadc5d54882427a3effb6534cca que corrige esta questão.
Parece que os elementos que estão com a Font Awesome declaradas em :before e :after não são compatíveis com a Font-family 'FontAwesome'. Tive que alterar para font-family: 'Font Awesome 5 Free';
Também alterei o bold para se adaptar a nova versão do FA.
