### ISSUE TITLE
Cliente não visualiza detalhamento de chamado em chamados da empresa.

### ISSUE THREAD

**Issue by pslauro** [LigeroSmart/ligerosmart#29]
Suporte bom dia.

Na tela de cliente, ao clicar em chamados da empresa há a listagem de todos os chamado, ao clicar em qualquer chamado, aparece a listagem de interações e ao clicar em qualquer interação...... a interação não aparece, ao invés disso pede login e senha novamente.
Em outros momentos aparece que o JavaScript não está ativado, independente do navegador.
Segue imagens como amostra.

![image](https://user-images.githubusercontent.com/25213559/110122491-7370a900-7d9e-11eb-957a-48e46e71e78b.png)

![image](https://user-images.githubusercontent.com/25213559/110122888-fb56b300-7d9e-11eb-9a53-bbc495c29a79.png)

**Comment by mfmatos** [comment]
Olá pslauro,

Tentei reproduzir esse problema em um ambiente novo e não consegui.

A instalação desse ambiente foi feita com o https://get.ligerosmart.com correto?
Há como executar o comando abaixo no seu servidor e nos reportar a saída?

```
docker logs ligerosmart-stack_web_1
