### ISSUE TITLE
Addon OCSIntegration: Erro ao executar integração manualmente

### ISSUE THREAD

**Issue by squidy** [LigeroSmart/ligerosmart#31]
Olá,
Estou testando o addon de integração com o OCS Inventory no Ligerosmart, mas está dando erro.
A instalação ocorre sem problemas. Fiz a configuração como manda o manual, e quando tento executar o comando para executar a integração manualmente (**bin/otrs.Console.pl Maint::Ocs::OcsIntegration**), aparecem erros conforme imagem abaixo:

![ligerosmart-ocsintegration](https://user-images.githubusercontent.com/43784/111795428-9078a200-889d-11eb-84a7-ecfa3e9b376b.png)

Verifiquei o arquivo que ele diz não ter encontrado e ele está no local correto, conforme abaixo:

![ligerosmart-ocsintegration2](https://user-images.githubusercontent.com/43784/111795529-ab4b1680-889d-11eb-8e56-86d501e3e4e0.png)

Versão do OCSIntegration: 6.0.2.0

**Comment by ricardosilvacomplemento** [comment]
[OcsIntegration-6.0.3.opm.zip](https://github.com/LigeroSmart/ligerosmart/files/6173032/OcsIntegration-6.0.3.opm.zip)

Olá @squidy boa tarde,

Temos uma nova release desse modulo, vou enviar por aqui pra você testar ok?

Qualquer problema estaremos a disposição.

Atenciosamente,

Ricardo Silva

**Comment by squidy** [comment]
Olá @ricardosilvacomplemento .

Fiz a instalação da nova versão... Agora quando tento executar o comando Maint::Ocs::OcsIntegration, aparece o log abaixo, e nada é mostrado na seção CMDB do Ligero:

> otrs@3c12829f05cc:~$ bin/otrs.Console.pl Maint::Ocs::OcsIntegration
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 154.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 222.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 330.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 343.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 428.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: "my" variable $YAMLObject masks earlier declaration in same scope at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 469.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: "my" variable $YAMLStr masks earlier declaration in same scope at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 470.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 533.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 548.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 803.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 872.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 926.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 954.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 990.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 1058.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 1112.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/Console/Command/Maint/Ocs/OcsIntegration.pm line 1140.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 204.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 283.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 303.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 307.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 445.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 522.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 523.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 527.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 615.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 628.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 637.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 670.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 683.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 692.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 728.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 741.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 758.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 797.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 833.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 842.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 851.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 860.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 869.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 878.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 933.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 942.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 951.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 960.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 969.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 978.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 984.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 1080.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 1089.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 1097.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationSnmp.pm line 1127.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 226.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 257.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 272.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 306.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 343.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 420.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 455.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 464.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 473.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 482.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 491.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 546.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 555.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 564.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 573.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 582.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 588.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 681.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 689.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 714.
> [Fri Mar 19 18:07:37 2021] otrs.Console.pl: push on reference is experimental at /opt/otrs/Kernel/System/OcsIntegrationComputer.pm line 867.
> ERROR: OTRS-otrs.Console.pl-Maint::Ocs::OcsIntegration-10 Perl: 5.22.1 OS: linux Time: Fri Mar 19 14:07:38 2021
> 
>  Message: Can't add new definition! The definition was not changed.
> 
>  Traceback (85962): 
>    Module: Kernel::System::ITSMConfigItem::Definition::DefinitionAdd Line: 280
>    Module: Kernel::System::Console::Command::Maint::Ocs::OcsIntegration::Run Line: 254
>    Module: (eval) Line: 460
>    Module: Kernel::System::Console::BaseCommand::Execute Line: 454
>    Module: Kernel::System::Console::InterfaceConsole::Run Line: 80
>    Module: bin/otrs.Console.pl Line: 36
> 
> ERROR: OTRS-otrs.Console.pl-Maint::Ocs::OcsIntegration-10 Perl: 5.22.1 OS: linux Time: Fri Mar 19 14:07:38 2021
> 
>  Message: Can't add new definition! The definition was not changed.
> 
>  Traceback (85962): 
>    Module: Kernel::System::ITSMConfigItem::Definition::DefinitionAdd Line: 280
>    Module: Kernel::System::Console::Command::Maint::Ocs::OcsIntegration::Run Line: 478
>    Module: (eval) Line: 460
>    Module: Kernel::System::Console::BaseCommand::Execute Line: 454
>    Module: Kernel::System::Console::InterfaceConsole::Run Line: 80
>    Module: bin/otrs.Console.pl Line: 36
> 
> ConfigItemIDs Founded 1.
> ERROR: OTRS-otrs.Console.pl-Maint::Ocs::OcsIntegration-10 Perl: 5.22.1 OS: linux Time: Fri Mar 19 14:07:38 2021
> 
>  Message: Need DefinitionID!
> 
>  Traceback (85962): 
>    Module: Kernel::System::ITSMConfigItem::Version::_FindChangedXMLValues Line: 1668
>    Module: Kernel::System::Console::Command::Maint::Ocs::OcsIntegration::Run Line: 561
>    Module: (eval) Line: 460
>    Module: Kernel::System::Console::BaseCommand::Execute Line: 454
>    Module: Kernel::System::Console::InterfaceConsole::Run Line: 80
>    Module: bin/otrs.Console.pl Line: 36
> 
> Updates NOT Founded ConfigItemID 1. Nothing to do.
> Done.

**Comment by ricardosilvacomplemento** [comment]
Olá novamente @squidy ,

Vamos verificar para remover esses alertas, porém pelo que acompanhei no seu log, aparentemente um item de configuração foi importado com sucesso correto?

**Comment by squidy** [comment]
Não era para aparecer na classe Computador no CMDB? Não está aparecendo nada.

![CMDB](https://user-images.githubusercontent.com/43784/111831568-f2e59880-88c5-11eb-95c1-1d4b0749b291.png)

**Comment by squidy** [comment]
Não era para aparecer na classe Computador do CMDB? Não está aparecendo nada..

![CMDB](https://user-images.githubusercontent.com/43784/111831776-35a77080-88c6-11eb-966e-b238d3fbf6fc.png)

**Comment by ricardosilvacomplemento** [comment]
Depende da sua configuração do modulo do OCS, por padrão o módulo vem configurado para criar uma nova classe chamada Computers:

<Setting Name="OcsIntegration::ComputerClass" Required="1" Valid="1">
        <Description Translatable="1">Computer Class.</Description>
        <Navigation>OcsIntegration::Core</Navigation>
        <Value>
            <Item ValueType="String">Computers</Item>
        </Value>
    </Setting>

Se não foi alterado ele criou essa nova classe no seu Ligero e a mesma aparece ai depois que permission group for configurado corretamente:

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/38730326/111832383-7a83d500-88cf-11eb-9f27-6a9cfc605441.png">

**Comment by ricardosilvacomplemento** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/38730326/111832539-b0c15480-88cf-11eb-81d9-292c5061f199.png">

**Comment by squidy** [comment]
Perfeito, @ricardosilvacomplemento.. Valeu!
