### ISSUE TITLE
BUG de formulário apagando formatação

### ISSUE THREAD

**Issue by rodgerfrancisco** [LigeroSmart/ligerosmart#5]
Bug de formulário apagando formatação ao começar a digitar e não deixa a alteração de campos pois fica descendo a página quando selecionarmos os campos a serem alterados. segue vídeo mostrando o bug
[t_video5098441405181723023.zip](https://github.com/LigeroSmart/ligerosmart/files/5702443/t_video5098441405181723023.zip)

**Comment by richieri** [comment]
Olá Rodger, vamos iniciar a verificação!

**Comment by juniorcunha** [comment]
@rodgerfrancisco pode me confirmar qual a versão do módulo "Forms" instalado?

**Comment by rodgerfrancisco** [comment]
@juniorcunha onde eu vejo isso? já pesquisei aqui na ferramenta e não acho

**Comment by juniorcunha** [comment]
@rodgerfrancisco na interface de agente, com um usuário administrador, acesse Administração -> Gerenciador de Pacotes, e procure no painel "Repositório Local" pelo módulo "Forms".

**Comment by rodgerfrancisco** [comment]
@juniorcunha segue:


Forms |   | 6.0.21 | Ligero | Crie formulários usando Campos Dinâmicos para cada S... | instalado
-- | -- | -- | -- | -- | --

**Comment by juniorcunha** [comment]
@rodgerfrancisco Faça o download do arquivo anexado nesta mensagem, descompacte e faça a instalação/atualização na interface de gerenciamento de pacotes. Após a atualização, limpe o cache do seu navegador e faça o teste novamente pra confirmar se problema será resolvido.
[Forms-6.0.22.opm.zip](https://github.com/LigeroSmart/ligerosmart/files/5778053/Forms-6.0.22.opm.zip)

**Comment by rodgerfrancisco** [comment]
@juniorcunha já estou de saída do trabalho, amanhã irei fazer isso depois que fizer o bkp e lhe confirmarei

**Comment by rodgerfrancisco** [comment]
Bom dia!

fui fazer o backup do OTRS utilizando o script da pasta /opt/otrs/scripts/backup.pl só que não deu certo e retornou a seguinte mensagem:
Backup /root/2021-01-07_11-50/Config.tar.gz ... done
Backup /root/2021-01-07_11-50/Application.tar.gz ... done
Dump MySQL data to /root/2021-01-07_11-50/DatabaseBackup.sql.gz ... mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
done

executei o comando como root, mas parece que está dando erro de permissão, mas o root não tem acesso a tudo?!

**Comment by rodgerfrancisco** [comment]
Para não perder tempo, fiz um SnapShot da máquina e instalei a atualização, testei e deu certo, está funcionando 100%. Para fins de curiosidade, o que estava acontecendo? Tinha algum código errado?

**Comment by richieri** [comment]
oi @rodgerfrancisco , Na verdade, essa issue já estava consertada pelo time de desenvolvimento pois havia sido reportada por um cliente anteriormente. Estava na etapa de QA. Fizemos e passamos pra ti. Agora vamos fazer o deploy.
Era um BUG de Javascript, em linhas gerais hehehehe.
Obrigado mais uma vez! Vou abrir uma nova issue sobre o erro de backup que você reportou. Obrigado!

**Comment by rodgerfrancisco** [comment]
Segue o erro:

Bom dia!

fui fazer o backup do OTRS utilizando o script da pasta /opt/otrs/scripts/backup.pl só que não deu certo e retornou a seguinte mensagem:
Backup /root/2021-01-07_11-50/Config.tar.gz ... done
Backup /root/2021-01-07_11-50/Application.tar.gz ... done
Dump MySQL data to /root/2021-01-07_11-50/DatabaseBackup.sql.gz ... mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
done

executei o comando como root, mas parece que está dando erro de permissão
