### ISSUE TITLE
Notificação de chamados via Telegram

### ISSUE THREAD

**Issue by diegoromal** [LigeroSmart/ligerosmart#56]
A notificações de chamados via telegram poderiam facilitar ainda mais a adesão para o usuário final à ferramenta de tickets.
Hoje eu sei que pode ser enviado usando a rota sendMessage com o id do usuário no telegram, neste formato:
https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=$CHATID&parse_mode=Markdown&text=$TEXTO

**Comment by richieri** [comment]
Diego, neste momento estamos atendendo este requisito através de Web Services, conforme documento abaixo:
https://docs.ligerosmart.org/kb/como-notificar-novos-chamados-no-telegram/
