### ISSUE TITLE
Integração RochetChat - Não cria WebService

### ISSUE THREAD

**Issue by victorfmaraujo** [LigeroSmart/ligerosmart#59]
Instalação Limpa

Debian 10 netinstall
VM com 8Gb de Ram e 4 processadores
Instalação limpa, após colcar o JavaScript do Rocketchat dentro de RocketChat::Code o webservice não é criado

olhando os logs pelo docker-compose logs a confirmação que não foi possível localizar o webservice

    web_1            | ERROR: GenericInterfaceProvider-10 Perl: 5.30.0 OS: linux Time: Fri May 7 12:05:31 2021
    web_1            |
    web_1            |  Message: Could not find valid web service for query string '/otrs/nph-genericinterface.pl/Webservice/RocketChat/?UserLogin=rocket.chat&Password=password'
    web_1            |
    web_1            |  RemoteAddress: 127.0.0.1
    web_1            |  RequestURI: /otrs/nph-genericinterface.pl/Webservice/RocketChat/?UserLogin=rocket.chat&Password=password
    web_1            |
    web_1            |  Traceback (39):
    web_1            |    Module: Kernel::GenericInterface::Provider::Run Line: 106
    web_1            |    Module: (eval) Line: 38
    web_1            |    Module: (eval) Line: 83
    web_1            |    Module: Plack::Sandbox::_2fapp_2epsgi::__ANON__[/app.psgi:94] Line: 82
    web_1            |    Module: CGI::Emulate::PSGI::__ANON__ (v0.23) Line: 30
    web_1            |    Module: Plack::Middleware::Static::call Line: 18
    web_1            |    Module: Plack::Component::__ANON__ Line: 50
    web_1            |    Module: Plack::Middleware::StackTrace::try {...}  Line: 38
    web_1            |    Module: (eval) (v0.30) Line: 100
    web_1            |    Module: Try::Tiny::try (v0.30) Line: 93
    web_1            |    Module: Plack::Middleware::StackTrace::call Line: 42
    web_1            |    Module: Plack::Component::__ANON__ Line: 50
    web_1            |    Module: (eval) Line: 145
    web_1            |    Module: Plack::Util::run_app Line: 145
    web_1            |    Module: Starman::Server::dispatch_request Line: 195
    web_1            |    Module: Starman::Server::process_request Line: 298
    web_1            |    Module: Net::Server::run_client_connection (v2.010) Line: 72
    web_1            |    Module: (eval) Line: 225
    web_1            |    Module: Net::Server::PreFork::run_child Line: 225
    web_1            |    Module: Net::Server::PreFork::run_n_children Line: 183
    web_1            |    Module: Net::Server::PreFork::loop Line: 107
    web_1            |    Module: Net::Server::run (v2.010) Line: 58
    web_1            |    Module: Starman::Server::run Line: 106
    web_1            |    Module: Plack::Handler::Starman::run Line: 25
    web_1            |    Module: Plack::Loader::Delayed::run Line: 20
    web_1            |    Module: Plack::Runner::run Line: 279
    web_1            |    Module: starman worker --port 9000 --workers 3 /app.psgi Line: 38
    web_1            | 172.18.0.5 - - [07/May/2021:09:05:31 -0300] "POST /otrs/nph-genericinterface.pl/Webservice/RocketChat/?UserLogin=rocket.chat&Password=password HTTP/1.1" 500 148 "-" "Go-http-client/1.1"

**Comment by mfmatos** [comment]
@richieri verifiquei que falta o procedimento de executar o RocketChat.pm do packagesetup na versão 6.1.3. Vou fazer um pull request com a correção.

**Comment by victorfmaraujo** [comment]
> 
> 
> @richieri verifiquei que falta o procedimento de executar o RocketChat.pm do packagesetup na versão 6.1.3. Vou fazer um pull request com a correção.

eu consigo corrigir de alguma forma pra ele executar  esse procedimento?

**Comment by mfmatos** [comment]
Com os comandos abaixo é possível testar com o código que submeti. Recomendo que seja feito em um ambiente de homologação.

Dentro da pasta ligerosmart-stack:
```
docker-compose run --rm -u otrs web git pull origin fix/rocketchat-integration
docker-compose run --rm -u otrs web otrs.Console.pl Maint::Database::Migration::Apply
```
Depois disso você acessa a interface web, vai em Administração > Web Services, edita o RocketChat e preenche o campo Validade com "válido". A partir daí o webservice ficará ativo.

Se você subiu o rocketchat em outro servidor, será preciso editar o XSLT do web service do RocketChat e mudar o IP da tag RocketChatAPIUrl com o endereço do seu servidor.

**Comment by victorfmaraujo** [comment]
> 
> 
> Com os comandos abaixo é possível testar com o código que submeti. Recomendo que seja feito em um ambiente de homologação.
> 
> Dentro da pasta ligerosmart-stack:
> 
> ```
> docker-compose run --rm -u otrs web git pull origin fix/rocketchat-integration
> docker-compose run --rm -u otrs web otrs.Console.pl Maint::Database::Migration::Apply
> ```
> 
> Depois disso você acessa a interface web, vai em Administração > Web Services, edita o RocketChat e preenche o campo Validade com "válido". A partir daí o webservice ficará ativo.
> 
> Se você subiu o rocketchat em outro servidor, será preciso editar o XSLT do web service do RocketChat e mudar o IP da tag RocketChatAPIUrl com o endereço do seu servidor.


Executei os comandos e o webservice não apareceu :/

**Comment by richieri** [comment]
Aqui aparentemente deu certo:

![image](https://user-images.githubusercontent.com/2002125/117492863-952a1000-af48-11eb-8fc5-ec4a14e7814e.png)

E o resultado:

![image](https://user-images.githubusercontent.com/2002125/117492902-a1ae6880-af48-11eb-92cf-069fbe86beeb.png)

O Web Service vem Inválido por padrão, é necessário habilitá-lo...

**Comment by mfmatos** [comment]
Ótimo. Vou preparar para a próxima versão

**Comment by victorfmaraujo** [comment]
eu rodei novamente o comando
docker-compose run --rm -u otrs web otrs.Console.pl Maint::Database::Migration::Apply
após isso funcionou.  Tudo certo por agora, obrigado.

**Comment by mfmatos** [comment]
Ótimo! Eu já gerei a versão 6.1.4 com a correção
