### ISSUE TITLE
Anexos enviados no Omnichannel do Rocket não estão subindo para o OTRS

### ISSUE THREAD

**Issue by richieri** [LigeroSmart/ligerosmart#6]
https://github.com/LigeroSmart/otrs.RocketChat/blob/d87945e210474141b0fdac902116b08c1de390fe/Kernel/GenericInterface/Operation/RocketChat/IncomingChat.pm#L238

**Comment by juniorcunha** [comment]
Implementação feita na brach: https://github.com/LigeroSmart/otrs.RocketChat/tree/feature/add-attachment-to-article

**Comment by richieri** [comment]
Teste concluído com sucesso

Rocket 3.11.0

LigeroSmart 3.0.1
