### ISSUE TITLE
Layout no celular.

### ISSUE THREAD

**Issue by diegoromal** [LigeroSmart/ligerosmart#63]
O menu lateral em um dispositivo móvel não funciona com o template do ligero, ao clicar nele, nenhuma ação é feita.

**Comment by mfmatos** [comment]
O elemento ResponsiveSidebarContainer está recebendo `display: none` e o menu de navegação não aparece no layout. Removendo no código o menu aparece.

![Captura de tela de 2021-06-16 11-28-09](https://user-images.githubusercontent.com/46325500/122238122-43a16900-ce96-11eb-879b-474cfbed04d2.png)

**Comment by mfmatos** [comment]
O teste dentro da função que expande o menu checa ao atributo 'left' e se for menor que zero ele faz a ação de expandir o menu.
Como no CSS há uma declaração deste elemento para o atributo left como 18px ele nunca fica menor que zero e o menu não aparece.

Linha referente ao CSS:
https://github.com/LigeroSmart/ligerosmart/blob/082720b46a6357b7bbedf11dd1465d05229185e6/var/httpd/htdocs/skins/Agent/ligero/css/Core.Default.css#L250

**Comment by mfmatos** [comment]
Corrigido na versão 6.1.9. A atualização pode ser feita com o comando `make upgrade-core` na pasta ligerosmart-stack. Estou à disposição caso precise de ajuda neste procedimento.

![Captura de tela de 2021-06-22 14-53-50](https://user-images.githubusercontent.com/46325500/122975447-ba90a300-d369-11eb-8b18-38ab9cf13e45.png)
