### ISSUE TITLE
Update do Elasticsearch para versão 7

### ISSUE THREAD

**Issue by marcelofmatos** [LigeroSmart/ligerosmart#91]
Venho testando a versão nova do Elasticsearch e está bem estável e rápido. Acho que seria bom verificarmos se é possível um upgrade neste servico na stack do LigeroSmart, que hoje por padrão e compatível com a versão 6

**Comment by mfmatos** [comment]
Criada configuração básica para testes:
https://github.com/LigeroSmart/ligerosmart-stack/tree/elasticsearch7

**Comment by marciocarvalho** [comment]
Alguma perspectiva de atualização do Elasticsearch da stack do LigeroSmart, visto que a versão utilizada atualmente contém vulnerabilidades graves conhecidas?

**Comment by mfmatos** [comment]
oi @marciocarvalho 

Informo que temos disponível no repositório a imagem da versão 6.8.23 que contém as correções até esta data. Você pode ver mais detalhes no link abaixo:

https://hub.docker.com/layers/ligero/elasticsearch/6.8.23/images/sha256-75cb9bad2d1ebea9340c091a57554a987f5b00accc7eb2129bbf2172fc8e4873?tab=layers

A versão do LigeroSmart compatível com a versão 7 do Elasticsearch está em fase de desenvolvimento.
