### ISSUE TITLE
AutoTicket não está funcionando.

### ISSUE THREAD

**Issue by pslauro** [LigeroSmart/ligerosmart#96]
Pessoal como estão tudo bem?
Tenho criado alguns AutoTickets onde os mesmos não estão funcionando.
Conforme solicitado, inclui eles em horários que certamente estavam dentro do horário comercial, algo como criação as 10 da manhã de uma quarta porém sem sucesso.
A única ocasião onde os AutoTickets funcionam é quando rodo o comando de criação na mão.

Não tenho no momento nenhuma evidencia, por favor me passem tudo que precisam como evidencia e seus respectivos comandos, terei prazer em ajudar e entregar os logs para resolvermos esse probleminha.

**Comment by mfmatos** [comment]
Oi Lauro,

Obrigado por sua colaboração.

Podes nos descrever aqui um passo-a-passo de como reproduzir este problema?

**Comment by pslauro** [comment]
Olá bom dia.

Ao criar o AutoTicket eu cheguei a realizar testes criando o ticket de um
dia para outro, o campo do auto ticket é criado porém é como se o cron não
estivesse rodando, o ticket e o agendamento dele só é criado quando é
realizado o comando manualmente otrs.Console.pl
Maint::AutoTicket::AutoTicketCron

Caso contrário nada acontece.

[image: image.png]

[image: image.png]

[image: image.png]



Em sex., 23 de jul. de 2021 às 07:41, mfmatos ***@***.***>
escreveu:

**Comment by richieri** [comment]
@pslauro @marcelofmatos vcs chegaram a resolver este problema, confere?

**Comment by pslauro** [comment]
Fala pessoal bom dia tudo bem? De fato resolveu.... porém... com ressalvas... lá no compose estava como America/Sao_Paulo e o @marcelofmatos disse que o normal era UTC.. porém... é assim... no America/Sao_Paulo... os tickets vem com horário certo.... tranquilo até ai... mas... no autoticket ele tem a diferença de Fuso... ele vê UTC e a solução foi mudarmos o horário para as 5 da manhã a execução para rodar como se fosse 2 da manhã.... Mas... se eu colocar em UTC... quem vem com a hora errada é o ticket.... e ai lembrei que lá atrás quando subi a minha instancia... foi colocando America/Sao_Paulo justamente por isso.

**Comment by mfmatos** [comment]
Confirmei em outro ambiente que tinha divergência do timezone dentro da configuração do container com o OTRSTimeZone. Fiz um trecho de código no Config.pm para detectar esse valor e incluir no OTRSTimeZone. Assim as configurações ficaram sincronizadas e também impede a sua alteração pela Configuração do Sistema.

https://github.com/LigeroSmart/ligerosmart/blob/07680c41551245ae9db10c177d97ac7d603d3225/Kernel/Config.pm#L46

**Comment by mfmatos** [comment]
Essa configuração foi removida porque em subprocessos chamados pelo framework o valor não estava sendo considerado da variável TZ, e usando UTC. 

A configuração está sendo aplicada na instalação do ambiente atravéz de script no container

https://github.com/LigeroSmart/docker-ligerosmart/blob/ba3803e8899e0c3ac071feea214270b0cb0d6340/base/app-init.d/01-default-time-zone.sh#L16
